version: '3.4'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: oxygen
      POSTGRES_PASSWORD: oxygen
      POSTGRES_DB: oxygen
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"